const bookFiles = [
  '30 Ways To Make Money Online.epub',
  'A Functional Approach To Java.epub',
  'Advanced Algorithms And Data Structures.epub',
  'Advanced Unity Game Development.epub',
  'AI Engineering.epub',
  'API Testing And Development With Postman.epub',
  'Art Of Java Web Development.pdf',
  'Artificial Intelligence - A Modern Approach.pdf',
  'AWS Certified Cloud Practitioner CLF-C02.epub',
  'Beginning Programming With Java For Dummies.epub',
  'Blood, Sweat, And Pixels.epub',
  'Building Micro-Frontends.epub',
  'Building Microservices, 2nd Edition.epub',
  'Clean Code Collection.epub',
  'Computer Science - Undergraduate Topics.pdf',
  'Designing Data-Intensive Applications.epub',
  'Designing Event-Driven Systems.pdf',
  'Developing Web Apps With Haskell And Yesod.epub',
  'Dietland.epub',
  'E-Commerce Business - The Ultimate Guide.epub',
  'El Triunfo De La Informacion.pdf',
  'Essential Postgres.epub',
  'Functional Programming In Scala.epub',
  'Functional Programming Simplified - Scala Edition.epub',
  'Functional Thinking - Paradigm Over Syntax.pdf',
  'Get Programming With Haskell.epub',
  'Grokking Algorithms.epub',
  'Hands-On Scala Programming.pdf',
  'Haskell In Depth.epub',
  'Intro.epub',
  'Java.epub',
  'Java For Web Development.epub',
  'JavaScript Cookbook, 3rd Edition.epub',
  'Kafka Streams In Action.epub',
  'Lean DevOps - A Practical Guide.epub',
  'Learning Concurrent Programming In Scala.epub',
  'Managing Humans.epub',
  'Mastering Kafka Streams And KsqlDB.epub',
  'Masters Of Doom.epub',
  'Men Explain Things To Me.epub',
  'Micro Frontends In Action.epub',
  'Modern Full-Stack Development.pdf',
  'Practice Makes Perfect.epub',
  'Pro Angular 16.pdf',
  'Programming In Scala, 4th Edition.pdf',
  'Programming In Scala, 5th Edition.pdf',
  'Programming Scala, 3rd Edition.epub',
  'React 17 Design Patterns.pdf',
  'React Hooks In Action.pdf',
  'Reactive Application Development.epub',
  'Reliable Source - Lessons From A Life In Software.epub',
  'Russian-English Visual Dictionary.pdf',
  'Russian Short Stories For Beginners.epub',
  'SBT In Action.epub',
  'Scala Cookbook, 2nd Edition.epub',
  'Scala In Action.epub',
  'Scala With Cats.epub',
  'Selected Poetry Of Marina Tsvetaeva.epub',
  'Seriously Good Software.pdf',
  'Siutico.epub',
  'Software Architecture In Practice - 2.epub',
  'Software Architecture In Practice.pdf',
  'Software Architecture - The Hard Parts.pdf',
  'Software Design Patterns.pdf',
  'Spring Boot In Practice.epub',
  'Street Coder.epub',
  'The Art Of Intrusion.epub',
  'The Art Of Postgres.pdf',
  'The Hundred-Page Machine Learning Book.epub',
  'The Illustrated AWS Cloud.pdf',
  'The Minimalist Entrepreneur.epub',
  'The New Penguin Russian Course.pdf',
  'Things You Need To Know About JVM.epub',
  'Understanding Distributed Systems.pdf',
  'Unity In Action, 3rd Edition.epub',
  'We Should All Be Feminists.epub',
  'XSS Attacks - Cross Site Scripting.pdf',
];

const COLORS = [
  '#4A6FA5', '#E07A5F', '#81B29A', '#F2CC8F', '#3D405B',
  '#6D597A', '#B56576', '#355070', '#EAAC8B', '#E56B6F',
  '#2A9D8F', '#E9C46A', '#264653', '#F4A261', '#606C38',
  '#DDA15E', '#BC6C25', '#283618', '#FEFAE0', '#6B705C',
];

// Known authors mapped by title
const AUTHORS = {
  'Designing Data-Intensive Applications': 'Martin Kleppmann',
  'Grokking Algorithms': 'Aditya Bhargava',
  'Building Microservices, 2nd Edition': 'Sam Newman',
  'Clean Code Collection': 'Robert C. Martin',
  'Software Architecture - The Hard Parts': 'Neal Ford, Mark Richards',
  'Software Architecture In Practice': 'Len Bass, Paul Clements, Rick Kazman',
  'Software Architecture In Practice - 2': 'Len Bass, Paul Clements, Rick Kazman',
  'Functional Thinking - Paradigm Over Syntax': 'Neal Ford',
  'Art Of Java Web Development': 'Neal Ford',
  'Pro Angular 16': 'Adam Freeman',
  'React 17 Design Patterns': 'Carlos Santana Roldan',
  'React Hooks In Action': 'John Larsen',
  'Modern Full-Stack Development': 'Frank Zammetti',
  'Hands-On Scala Programming': 'Haoyi Li',
  'Programming In Scala, 4th Edition': 'Martin Odersky',
  'Programming In Scala, 5th Edition': 'Martin Odersky',
  'Programming Scala, 3rd Edition': 'Dean Wampler',
  'Seriously Good Software': 'Marco Faella',
  'Understanding Distributed Systems': 'Roberto Vitillo',
  'The Illustrated AWS Cloud': 'Jen Looper, Denise Yu',
  'XSS Attacks - Cross Site Scripting': 'Seth Fogie, Jeremiah Grossman',
  'Software Design Patterns': 'Sufyan bin Uzayr',
  'Computer Science - Undergraduate Topics': 'Bhim P. Upadhyaya',
  'Artificial Intelligence - A Modern Approach': 'Stuart Russell, Peter Norvig',
  'The New Penguin Russian Course': 'Nicholas J. Brown',
  'Russian-English Visual Dictionary': 'DK Publishing',
  'Designing Event-Driven Systems': 'Ben Stopford',
  'The Art Of Postgres': 'Dimitri Fontaine',
  'Essential Postgres': 'Craig Kerstiens',
  'Mastering Kafka Streams And KsqlDB': 'Mitch Seymour',
  'Kafka Streams In Action': 'Bill Bejeck',
  'Blood, Sweat, And Pixels': 'Jason Schreier',
  'Masters Of Doom': 'David Kushner',
  'Men Explain Things To Me': 'Rebecca Solnit',
  'We Should All Be Feminists': 'Chimamanda Ngozi Adichie',
  'Dietland': 'Sarai Walker',
  'The Art Of Intrusion': 'Kevin Mitnick',
  'Managing Humans': 'Michael Lopp',
  'Street Coder': 'Sedat Kapanoglu',
  'The Minimalist Entrepreneur': 'Sahil Lavingia',
  'The Hundred-Page Machine Learning Book': 'Andriy Burkov',
  'Selected Poetry Of Marina Tsvetaeva': 'Marina Tsvetaeva',
  'Building Micro-Frontends': 'Luca Mezzalira',
  'Micro Frontends In Action': 'Michael Geers',
  'Haskell In Depth': 'Vitaly Bragilevsky',
  'Get Programming With Haskell': 'Will Kurt',
  'Scala With Cats': 'Noel Welsh, Dave Gurnell',
  'Scala Cookbook, 2nd Edition': 'Alvin Alexander',
  'Functional Programming Simplified - Scala Edition': 'Alvin Alexander',
  'Functional Programming In Scala': 'Paul Chiusano, Runar Bjarnason',
  'Scala In Action': 'Nilanjan Raychaudhuri',
  'SBT In Action': 'Joshua Suereth, Matthew Farwell',
  'Learning Concurrent Programming In Scala': 'Aleksandar Prokopec',
  'A Functional Approach To Java': 'Ben Weidig',
  'Spring Boot In Practice': 'Somnath Musib',
  'JavaScript Cookbook, 3rd Edition': 'Adam Scott, Matthew MacDonald',
  'Lean DevOps - A Practical Guide': 'Robert Benefield',
  'AWS Certified Cloud Practitioner CLF-C02': 'David Clinton',
  'Reactive Application Development': 'Duncan DeVore, Sean Walsh',
  'Unity In Action, 3rd Edition': 'Joe Hocking',
  'Advanced Unity Game Development': 'Victor Brusca',
  'Advanced Algorithms And Data Structures': 'Marcello La Rocca',
  'API Testing And Development With Postman': 'Dave Westerveld',
  'AI Engineering': 'Chip Huyen',
  'El Triunfo De La Informacion': 'Cesar Hidalgo',
};

export const books = bookFiles.map((file, i) => {
  const type = file.endsWith('.pdf') ? 'pdf' : 'epub';
  const title = file.replace(/\.(epub|pdf)$/, '');
  const author = AUTHORS[title] || '';
  return {
    id: i,
    title,
    author,
    file,
    type,
    color: COLORS[i % COLORS.length],
  };
});

export function getBook(id) {
  return books.find((b) => b.id === Number(id));
}
